### ISSUE TITLE
RDS Postgres has plan changes immediately after apply

### ISSUE THREAD

**Issue by firasnajjar** [terraform-providers/terraform-provider-alicloud#969]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
→ terraform version
Terraform v0.11.13
+ provider.alicloud v1.37.0
```
### Affected Resource(s)
- alicloud_db_account
- alicloud_db_backup_policy

### Terraform Configuration Files
```hcl
provider "alicloud" {
  access_key = "*****************"
  secret_key = "*****************"
  region = "cn-shanghai"
  version = "1.37"
}

resource "alicloud_vpc" "vpc" {
  name       = "test_vpc"
  cidr_block = "10.0.0.0/8"
}

resource "alicloud_vswitch" "vsw" {
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.0.0/24"
  availability_zone = "cn-shanghai-e"
  name              = "rds_subnet"
}

resource "alicloud_db_instance" "postgres" {
  engine            = "PostgreSQL"
  engine_version    = "10.0"
  instance_type     = "pg.n2.medium.1"
  instance_storage  = "100"
  instance_name     = "test_postgres"
  zone_id           = "cn-shanghai-e"
  vswitch_id        = "${alicloud_vswitch.vsw.id}"
  security_ips      = ["${alicloud_vswitch.my_subnet.cidr_block}"]
}

resource "alicloud_db_account" "postgres_account" {
  instance_id       = "${alicloud_db_instance.postgres.id}"
  name              = "blabla"   //the account name cannot have capital letters
  password          = "***********"
  description       = "description"
}

resource "alicloud_db_backup_policy" "default" {
  instance_id       = "${alicloud_db_instance.postgres.id}"
  backup_period     = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
  retention_period  = 7
  log_backup        = true
  log_retention_period = 7
}

resource "alicloud_vswitch" "my_subnet" {
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.1.0/24"
  availability_zone = "cn-shanghai-e"
  name              = "my_subnet"
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
Irrelevant.

### Expected Behavior
Running `terraform plan` immediately after running `terraform apply` should result in NO CHANGES.

### Actual Behavior
The plan result immediately after applying is the following:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ alicloud_db_account.cf_postgres_account
      type:                 "Super" => "Normal"

  ~ alicloud_db_backup_policy.default
      log_backup:           "false" => "true"
      log_retention_period: "0" => "7"


Plan: 0 to add, 2 to change, 0 to destroy.

------------------------------------------------------------------------

```

### Steps to Reproduce
1. `terraform apply`
1. `terraform plan`

### Important Factoids
Running in Shanghai region as you can see in the code. I'm using a domestic account, not an international one.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? Yes, both of those:

- https://github.com/alibaba/terraform-provider/issues/764 
- https://github.com/alibaba/terraform-provider/issues/768

They are from the deprecated repository.

In addition, I know that the account type is relevant only with MySql. That's why it's not used in the code at all. 

I also noticed that the log backup and log retention period are not updated on the instance after applying the code. I checked this in the web portal of my Alicloud account.

**Comment by AJenpan** [comment]
- I am sorry to tell you, alicloud_db_backup_policy does not support the PostgreSQL/PPAS Basic Edition. 
[detail](https://www.alibabacloud.com/help/doc-detail/55665.htm#h2-url-4.)
- About alicloud_db_account Resource, PostgreSQL, PPAS, SQL Server 2017 clustered edition has and only has one high-privileged account. and I fixed it.  [detail](https://www.alibabacloud.com/help/doc-detail/26263.htm)

**Comment by firasnajjar** [comment]
* Do you mean that the log_backup is not supported in the "Basic Edition"? The backup policy works fine with it. The only problem is the logs. In addition, according to the link you attached, backup is supported. Only log management isn't. In addition, if log_backup cannot be enabled on the "Basic Edition", then why its value is by default true in terraform? This means that if I'm using the "Basic Edition", I must set it to false manually. Shouldn't the default be false and if I'm using the HA edition then I can enable it if I want to. Or make the default true only if the type is HA and make the default false in the "Basic Edition". The point is if I'm using the "Basic Edition", I know that the feature of log_backup is not supported and I need to write this down every time!

* What was fixed exactly? The documentation? The API? Terraform? Again, this is optional and defaults to "Normal". Does this mean that I always must set this to "Super"?

**Comment by firasnajjar** [comment]
A new issue is introduced. If you run the following: 
```
variable "region" {
  default = "eu-central-1"
}

variable "zone" {
  default = "eu-central-1a"
}

provider "alicloud" {
  access_key = "**"
  secret_key = "**"
  region = "${var.region}"
  version = "1.39"
}

resource "alicloud_vpc" "vpc" {
  name       = "some_name"
  cidr_block = "10.0.0.0/8"
}

resource "alicloud_vswitch" "vsw" {
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.0.0/24"
  availability_zone = "${var.zone}"
  name              = "rds_subnet"
}



resource "alicloud_db_instance" "cf_postgres" {
  engine            = "PostgreSQL"
  engine_version    = "10.0"
  instance_type     = "pg.n2.medium.1"
  instance_storage  = "20"
  instance_name     = "my_bla"
  zone_id           = "${var.zone}"
  vswitch_id        = "${alicloud_vswitch.vsw.id}"
  security_ips      = ["${alicloud_vswitch.dmz.cidr_block}"]
}

//credentials for accessing the db
resource "alicloud_db_account" "cf_postgres_account" {
  instance_id       = "${alicloud_db_instance.cf_postgres.id}"
  name              = "batata"   //the account name cannot have capital letters
  password          = "***"
  type              = "Super"
}

//backup policy
resource "alicloud_db_backup_policy" "default" {
  instance_id       = "${alicloud_db_instance.cf_postgres.id}"
  backup_period     = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

  retention_period  = 7
  log_backup        = false
//  log_retention_period = 7
}


resource "alicloud_vswitch" "dmz" {
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.1.0/24"
  availability_zone = "${var.zone}"
  name              = "dmz_subnet"
}

output "cf_postgress_connection_string" {
  value = "${alicloud_db_instance.cf_postgres.connection_string}"
}

output "cf_postgress_port" {
  value = "${alicloud_db_instance.cf_postgres.port}"
}
```
I get the following error: 

```
Error: Error applying plan:

1 error(s) occurred:

* alicloud_db_backup_policy.default: 1 error(s) occurred:

* alicloud_db_backup_policy.default: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_db_backup_policy.go:155:
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_rds.go:437: Resource pgm-gw85l6vh41j12w2x ModifyBackupPolicy Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: InvalidLogBackupRetentionPeriod.Malformed
Recommend: 
RequestId: FA21CAFA-B00A-4CD3-9BB3-74B587FDAA59
Message: The Specified LogBackupRetentionPeriod is not valid.
```
In addition, I tried to remove the comment on the line with the backup retention period and configure it to 7 although this is meaningless since the log backup is disabled. This didn't solve the issue and I got the same error. 

In the console I can see that the backup was configured correctly. But terraform fails. Another new thing that happens now, if I run terraform apply again I get the following error:
```
  ~ alicloud_db_backup_policy.default
      backup_time: "07:00Z-08:00Z" => "02:00Z-03:00Z"
```
Although I didn't change the backup time at all!! Why does it want to change it!!!

Then, I tried to run: `terraform destroy` and I got the following error:

```
1 error(s) occurred:

* alicloud_vpc.vpc (destroy): 1 error(s) occurred:

* alicloud_vpc.vpc: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_vpc.go:214: Resource vpc-gw81n1v3audl0no8cr4s7 DeleteVpc Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: DependencyViolation.SecurityGroup
Recommend: 
RequestId: 80E10DD1-0E04-4F42-B5C3-90CE0F30496A
Message: Specified object has dependent resources

```
 
This error of deleting the VPC was opened a while ago [here](https://github.com/alibaba/terraform-provider/issues/764).

Now I have a VPC that I cannot delete although it has no security groups at all, in contrary to what the error says...

In addition, the issue with the log retention period is new. And when I apply terraform on a database that was created a week ago or so everything works fine.

**Comment by firasnajjar** [comment]
In addition, if I try to create a "Basic Edition" database in the portal, it works, and by default it is configured with backup turned on with 7 days retention and daily backup configured. The retention days, and the log backup cannot be edited in the portal. The days on which the backup is taken and the backup time can be changed in the portal.

**Comment by AJenpan** [comment]
```tf
Error: Error applying plan:

1 error(s) occurred:

* alicloud_db_backup_policy.default: 1 error(s) occurred:

* alicloud_db_backup_policy.default: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_db_backup_policy.go:155:
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_rds.go:437: Resource pgm-gw85l6vh41j12w2x ModifyBackupPolicy Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: InvalidLogBackupRetentionPeriod.Malformed
Recommend: 
RequestId: FA21CAFA-B00A-4CD3-9BB3-74B587FDAA59
Message: The Specified LogBackupRetentionPeriod is not valid.
```
this is confirmed to be a bug, Thanks for your feedback.

**Comment by lemondlut** [comment]
> * Do you mean that the log_backup is not supported in the "Basic Edition"? The backup policy works fine with it. The only problem is the logs. In addition, according to the link you attached, backup is supported. Only log management isn't. In addition, if log_backup cannot be enabled on the "Basic Edition", then why its value is by default true in terraform? This means that if I'm using the "Basic Edition", I must set it to false manually. Shouldn't the default be false and if I'm using the HA edition then I can enable it if I want to. Or make the default true only if the type is HA and make the default false in the "Basic Edition". The point is if I'm using the "Basic Edition", I know that the feature of log_backup is not supported and I need to write this down every time!

> * What was fixed exactly? The documentation? The API? Terraform? Again, this is optional and defaults to "Normal". Does this mean that I always must set this to "Super"?

Above two questions, please 
1 refer documentation:(Waiting Merged)
https://github.com/AJenpan/terraform-provider-alicloud/blob/2c91bd58ca60328e56d273810f9ba54b0b5867d9/website/docs/r/db_backup_policy.html.markdown;
2 PR Merged
https://github.com/terraform-providers/terraform-provider-alicloud/pull/1056

**Comment by lemondlut** [comment]
> ```terraform
> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * alicloud_db_backup_policy.default: 1 error(s) occurred:
> 
> * alicloud_db_backup_policy.default: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_db_backup_policy.go:155:
> [ERROR] terraform-provider-alicloud/alicloud/service_alicloud_rds.go:437: Resource pgm-gw85l6vh41j12w2x ModifyBackupPolicy Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
> SDK.ServerError
> ErrorCode: InvalidLogBackupRetentionPeriod.Malformed
> Recommend: 
> RequestId: FA21CAFA-B00A-4CD3-9BB3-74B587FDAA59
> Message: The Specified LogBackupRetentionPeriod is not valid.
> ```
> 
> this is confirmed to be a bug, Thanks for your feedback.

@firasnajjar , also, this bug has been fixed by #1056
